#!/bin/bash

check=70
path="/home/vboxuser/1ext/LOG"

size=`df -h $path --output=pcent | grep -o "[0-9]*"`
if [ "$size" -ge "$check" ]
then
  tar -czf archive.tar.gz -C /home/vboxuser/1ext LOG
  sudo mv archive.tar.gz /home/vboxuser/2ext/BACKUP/archive.tar.gz
  sudo rm -f /home/vboxuser/1ext/LOG/*
fi
